version: '3.3'
services:
  #db:
  #  build:
  #    context: ./sql
  #    dockerfile: Dockerfile
  #  container_name: sqlDB
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: imse4eva
  #    MYSQL_USER: devuser
  #    MYSQL_PASSWORD: devpass
  #    MYSQL_DATABASE: imse_sql_db
  #  ports:
  #    - "3306:3306"
  #  links:
  #  - web
  #  - db_import


  db_import:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: db_import
    volumes:
    - ./python/resources:/opt/resources
    networks:
    - default
    expose:
    - "80"
   # depends_on: 
   # - db


    
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./php/html:/var/www/html/
    networks:
    - default
    ports:
      - "8000:80"
    restart: on-failure
   # depends_on: 
   # - db


networks:
  default:

