version: '3.3'
services:

  db:
    # no Dockerfile needed
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=imse_sql_db
    - MYSQL_USER=devuser
    - MYSQL_PASSWORD=devpass
    networks:
    - default
    restart: always
    expose:
    - "3306"

  db_import:
    build:
      # go to db_import directory to automatically find Dockerfile 
      context: db_import
      dockerfile: Dockerfile
    environment:
    - DB_URI=mysql://devuser:devpass@db:3306/imse_sql_db
    volumes:
    - ../python/db_import/resources:/resources
    networks:
    - default
    expose:
    - 80
    depends_on:
    - db
    
  web:
    build:
      context: ../php
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ../php/html:/var/www/html/
    networks:
    - default
    ports:
      - "8000:80"
    depends_on:
      - db

networks:
  default:

