# base image
#FROM oraclelinux:8
FROM ghcr.io/oracle/oraclelinux8-instantclient:21

# Sql scripts to setup database
COPY scripts /docker-entrypoint-initdb.d

# Confirm sqlplus is working
#    no output in terminal during runtime, but works manually
CMD ["sqlplus", "-v"]

###############################################################
# echo $PATH
#    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# -> was heisst das?
#
#
# To use binaries from the tools package, use yum or dnf to install the package and then update your PATH environment variable. For example:
#  $ export PATH=/usr/lib/oracle/21/client64/bin:$PATH
#
#
#
