version: '3.3'
services:

  db:
    image: mysql:latest
    container_name: db
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=imse_sql_db
    - MYSQL_USER=devuser
    - MYSQL_PASSWORD=devpass
    networks:
    - default
    restart: always
    expose:
    - "3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_import:
    build:
      context: ../python
      dockerfile: Dockerfile
    container_name: db_import
    environment:
    - DB_URI=mysql://devuser:devpass@db:3306/imse_sql_db
    volumes:
    - ../python/db_import/csv:/csv
    - ../python/db_import/resources:/resources
    networks:
    - default
    expose:
    - "80"
    restart: on-failure
    depends_on:
    - db
    links: 
    - db
    
  web:
    build:
      context: ../php
      dockerfile: Dockerfile
    container_name: web
    restart: on-failure
    volumes:
      - ../php/html:/var/www/html/
    networks:
    - default
    ports:
      - "8000:80"
    depends_on:
      - db

networks:
  default:

