version: '3.3'
services:
  db_import:
    build:
      context: ../python/
      dockerfile: Dockerfile
    container_name: db_import
    volumes:
    - ../python/db_import/resources:/var/resources
    - ../python/db_import:/opt/db_import
    networks:
    - default
    expose:
    - "80"

    
  web:
    build:
      context: ../php
      dockerfile: Dockerfile
    container_name: web
    restart: on-failure
    volumes:
      - ../php/html:/var/www/html/
    networks:
    - default
    ports:
      - "8000:80"


networks:
  default:

